repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: generate-structure-doc
        name: Generate docs/estructura.md
        entry: python scripts/generate_tree.py
        language: system
        pass_filenames: false
        stages: [pre-commit]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML"]
