###############################################
# Reglas del bot (configuración funcional)    #
# - TODAS las opciones funcionales van aquí.  #
# - Secretos y tokens van en .env             #
# - Puedes crear overrides por chat/canal     #
###############################################

default:
  # Encendido general del bot por canal/grupo
  enabled: true                  # Si es false, el bot ignora mensajes en este chat/canal

  # Metadatos y textos base del bot
  bot_name: "AtencionClienteBot" # Nombre del bot (sólo informativo/logs)
  locale: "es"                   # Idioma principal
  greetings_enabled: true        # (obsoleto, usar greeting_enabled)
  greeting_enabled: true         # Si es true, el bot muestra el saludo antes del menú
  # Mostrar saludo y menú automáticamente en el primer mensaje si parece un saludo corto (e.g., "hola", "buenas").
  # Si el primer mensaje del usuario parece una intención (varias palabras), el bot prioriza la intención.
  greeting_force_on_first_message: true
  # Mostrar un prompt en el saludo para ofrecer el menú solo si se solicita (cuando los menús estén habilitados)
  greeting_menu_prompt_enabled: true
  greeting_menu_prompt_text: "Cuéntame, ¿en qué te puedo ayudar hoy?😎 

  
   Si quieres, también puedo mandarte el menú con todas las opciones disponibles."
  # Segundos de retraso entre el saludo y el mensaje de prompt (float o int)
  greeting_menu_prompt_delay: 2
  greeting_ttl_days: 7          # Repetir saludo automáticamente después de N días (0 = nunca repetir)
  greeting_text: |               # Puedes personalizar este saludo. Si greeting_enabled es false, no se muestra.
    ¡Hola Bienvenid@ a Urban elegance ! Soy tu asistente virtual.
  fallback_text: "No entendí tu mensaje. dime si quieres ver las opciones del menú." # Respuesta por defecto si no se reconoce la entrada

  # =============================
  # Memoria conversacional (historial y temas)
  # =============================
  memory:
    enabled: true               # Registrar historial y temas abiertos
    history_max: 100            # Máximo de mensajes por usuario/chat en memoria
    # NUEVO: Duración flexible para ofrecer retomar conversación.
    # Usa 'resume_after' con unidades (recomendado): "30m", "2h", "1d".
    # Retrocompatibilidad: si 'resume_after_minutes' está presente, tiene prioridad.
    resume_after: "60m"         # Tiempo de inactividad para ofrecer retomar (m/h/d)
    resume_after_minutes: 60    # (Legacy) Ofrecer retomar si vuelve después de X minutos
    topic_ttl_days: 14          # Tiempo de vida de un tema abierto (días)
    offer_resume_message: "Veo que tenías pendiente: {topic}. ¿Quieres continuar?"
    history_command_enabled: true
    history_privacy_mask_emails: true

    # =============================
    # Inactividad (recordatorio y cierre automático)
    # =============================
    inactivity:
      enabled: true
      # Enviar un recordatorio si el usuario no responde tras este tiempo.
      # Formatos soportados: "30m" (minutos), "2h" (horas), "1d" (días), "1h 30m".
      reminder_after: "3m"
      reminder_message: "¿Sigues ahí? Si necesitas ayuda, puedes contarme más o escribe 'menu' para ver opciones."
      # Cerrar el chat si no hay respuesta tras este tiempo.
      close_after: "5m"
      close_message: "He cerrado el chat por inactividad. Si necesitas algo más, escribe de nuevo para empezar un nuevo tema."
      # Enviar el recordatorio solo una vez por inactividad
      send_reminder_once: true
      # Estados del bot que se consideran 'esperando respuesta del usuario'
      monitor_states: ["ticket:ask_detail"]


  # Encendido/apagado de funcionalidades principales (features)
  # Puedes desactivar FAQ, tickets, escalación, etc. por canal o global
  features:
    connectors:
      telegram_enabled: true     # Conector Telegram activo (requiere TELEGRAM_TOKEN en .env)
      webchat_enabled: true      # Conector Webchat activo
      whatsapp_enabled: true     # Conector WhatsApp activo (requiere tokens .env)
    faq:
      enabled: true              # Respuestas automáticas de FAQ
      not_found_message: "No encontré esa pregunta en el FAQ. ¿Quieres crear un ticket?"
      # Umbral de similitud para considerar que un mensaje es una pregunta del FAQ.
      # Valor entre 0.0 y 1.0 (mayor = más estricto). Ejemplo: 0.75
      match_threshold: 0.75
    tickets:
      enabled: true              # Gestión de tickets
      category_options: ["general", "facturacion", "tecnico"]
      default_priority: "normal"
    escalation:
      enabled: true              # Escalamiento a agente humano
      request_contact_fields: ["nombre", "correo"]

  # =============================
  # Catálogo configurable
  # Puedes poner el link de tu catálogo aquí y cambiar el texto que verá el usuario.
  catalog:
    enabled: true
    link: "https://drive.google.com/drive/folders/1AJG-4rTitxN8usuNeYy2gO9RZgSQ8VD1"
    # Mensaje final mostrado al usuario (editable desde aquí). Mantener el link sólo en este bloque.
    message: "Puedes ver nuestro catálogo completo aquí: https://drive.google.com/drive/folders/1AJG-4rTitxN8usuNeYy2gO9RZgSQ8VD1"

  # Redes sociales y contactos (configurable por el usuario)
  socials:
    instagram: "https://www.instagram.com/urban.elegance2.0?igsh=dXc0Z2Z1bmNpM2xo"


  # =============================
  # Sinónimos (atajos globales)
  # =============================
  # Palabras/atajos que el bot reconoce en cualquier estado para ciertos flujos.
  # Se usan como apoyo a NLU e interpretación rápida fuera de menús.
  synonyms:
    menu: ["menu", "menú", "/start", "inicio", "empezar", "hola", "buenas"]
    # Frases de aceptación para que el usuario pida el menú tras el saludo
    menu_accept: ["si", "sí", "menu", "menú", "ver menu", "ver menú", "opciones", "ver opciones", "dame el menú", "dame el menu", "quiero el menu"]
    faq: ["faq", "preguntas", "ayuda", "info", "informacion", "información"]
    ticket: ["ticket", "soporte", "reclamo", "incidencia", "abrir ticket", "crear ticket", "abrirr tiket", "tickets"]
    agent: ["agente", "humano", "asesor", "representante", "hablar con agente", "soporte humano", "quiero humano"]


  # =============================
  # Menús dinámicos configurables
  # =============================
  # Si 'menus.items' está definido, el bot usará esta estructura en lugar del menú clásico.
  # Puedes definir cualquier cantidad de menús y submenús, con las opciones y acciones que desees.
  # Cada opción puede tener triggers (palabras o números que la activan), acción y destino.
  # Para ocultar un menú o una opción, usa 'enabled: false'.
  # Ejemplo: para ocultar el submenú ventas_menu, pon 'enabled: false' en ese bloque.
  menus:
    enabled: true
    root: main
    items:
      main:
        text: |
          ¿Cómo podemos ayudarte hoy?

          1️⃣ Información de productos y precios
          2️⃣ Soporte técnico y reclamos
          3️⃣ Estado de mi pedido o ticket
          4️⃣ Hablar con un asesor humano
          5️⃣ Catálogo y productos
          9️⃣ Ver más opciones
        options:
          - triggers: ["1", "productos", "precios", "catálogo", "faq"]
            action: goto
            target: faq_menu
            enabled: true
          - triggers: ["2", "soporte", "reclamo", "ticket", "problema", "crear ticket"]
            action: ticket_ask_detail
            enabled: true
          - triggers: ["3", "estado", "pedido", "consultar ticket", "ver ticket"]
            action: consultar_ticket
            enabled: true
          - triggers: ["4", "asesor", "humano", "agente", "hablar con agente"]
            action: escalation
            enabled: true
          - triggers: ["9", "más", "opciones", "menu"]
            action: goto
            target: extra_menu
            enabled: true
          - triggers: ["5", "catalogo", "catálogo", "productos"]
            action: reply
            # Respuesta amable y profesional para el catálogo. Edita `default.catalog.link` si quieres cambiar la URL.
            reply_text: "¡Genial! {catalog.message}\n\nSi quieres, puedo enviarte novedades o promociones cuando salgan. ¿Te interesa recibir alertas?"
            enabled: true
      faq_menu:
        text: |
          Pregúntame sobre cualquier tema: precios, productos, catálogo, envíos, pagos, devoluciones...
          Escribe 9 o 'menú' para volver al menú principal.
        options:
          - triggers: ["9", "menu", "volver", "back"]
            action: back
      extra_menu:
        text: |
          Otras opciones:
          1️⃣ Información de la empresa
          2️⃣ Formas de pago y envíos
          9️⃣ Volver al menú principal
        options:
          - triggers: ["1", "empresa", "quiénes son"]
            action: goto
            target: faq_menu
            enabled: true
          - triggers: ["2", "pago", "envíos", "formas de pago"]
            action: goto
            target: faq_menu
            enabled: true
          - triggers: ["9", "volver", "menu"]
            action: back

  # =============================
  # NLU simple configurable (intents y saludos)
  # =============================
  # Define saludos y patrones de intención para orientar al usuario sin tocar código.
  nlu:
    greetings:
      enabled: true
      triggers: ["/start", "hola", "buenas", "hello", "hi", "hey", "menu"]
    threshold: 0.78
    low_confidence_message: "Para ayudarte mejor puedo: mostrar el menú, crear un ticket o derivarte a un agente. ¿Qué prefieres?"
    provider: ml
    ml:
      retrain_on_start: false        # true para reentrenar en cada arranque (dev)
      model_path: data/models/nlu_nb.pkl
      char_ngrams: [3, 5]
      word_ngrams: [1, 2]
      alpha: 1.0
    intents:
      - name: ver_menu
        patterns: ["ver menu", "ver menú", "menu", "opciones", "inicio", "empezar"]
        action: goto
        target: main
      - name: ver_historial
        patterns: ["historial", "/historial", "ver historial", "mis mensajes"]
        action: reply
        reply_text: "Mostrando tu historial reciente…"
      - name: continuar
        patterns: ["continuar", "/continuar", "seguir", "retomar"]
        action: reply
        reply_text: "Retomando donde lo dejamos…"
      - name: abrir_ticket
        patterns: ["abrir ticket", "crear ticket", "tengo un problema", "reclamo", "soporte", "abrirr tiket", "tickets", "necesito soporte"]
        action: ticket_ask_detail
      - name: hablar_agente
        patterns: ["hablar con agente", "asesor", "humano", "agente", "soporte humano", "quiero humano", "quiero hablar con humano"]
        action: escalation
      - name: faq
        patterns: ["faq", "preguntas", "precios", "planes", "información", "informacion"]
        action: goto
        target: faq_menu
      - name: ver_catalogo
        patterns: ["catalogo", "catálogo", "ver catálogo", "ver el catálogo", "quiero ver el catálogo", "productos", "ver productos", "me gustaría ver el catálogo", "me gustaria ver el catalogo"]
        action: reply
        # Respuesta más formal y profesional. Usa {catalog.link} o {catalog.message} según prefieras.
        reply_text: "Perfecto. Puede ver nuestro catálogo completo aquí: {catalog.link}\n\n¿Desea que le envíe novedades o promociones cuando haya lanzamientos?"
      - name: novedades
        patterns: ["novedades", "lanzamientos", "nueva colección", "novedad"]
        action: reply
        reply_text: "Cada semana publicamos novedades. Puedes ver las últimas aquí: https://tusitio.com/novedades. ¿Deseas que te avise cuando lancemos algo nuevo?"
      - name: consultar_ticket
        patterns: ["ver ticket", "consultar ticket", "estado ticket", "/ticket"]
        action: reply
        reply_text: "Para consultar un ticket escribe: /ticket <id>. Por ejemplo: /ticket 123"
      - name: despedida
        patterns: ["gracias", "muchas gracias", "listo", "hasta luego", "adios", "adiós"]
        action: reply
        reply_text: "¡Con gusto! Si necesitas algo más, estoy aquí para ayudarte."
      - name: satisfaccion
        patterns: ["que bien", "está bien", "está bien", "ok", "perfecto", "me gusta", "excelente", "super", "chévere", "listo", "muy bien", "genial", "buenísimo", "aprobado", "funciona", "me encanta"]
        action: reply
        # Respuestas en tono formal (usted) para mayor profesionalidad
        responses:
          - "Me alegra que le haya resultado útil. Si necesita algo más, con gusto le atiendo."
          - "Perfecto. Recuerde que puede consultar el menú o solicitar novedades cuando lo desee."
          - "Excelente. Si tiene otra consulta, por favor indíquemela y con gusto la atenderé."
          - "Me alegra saberlo. ¿Desea que le envíe el catálogo o información sobre promociones?"
          - "Gracias por su comentario. Estoy a su disposición para cualquier otra gestión."
  # =============================
  # Base de conocimiento (FAQ)
  # =============================
  # Aquí defines las preguntas y respuestas que el bot usará en el submenú FAQ.
  # Puedes agregar tantas como quieras. El bot busca coincidencias por palabra clave.
  faq:
  - q: "¿Qué puedes hacer?"
    keywords: ["qué puedes hacer", "qué haces", "qué opciones hay", "cómo me puedes ayudar", "ayuda", "servicios", "funcionalidades", "qué ofrece el bot"]
    a: "{auto}"
  - q: "horario"
    keywords: ["horario", "a qué hora abren", "a qué hora cierran", "hasta qué hora", "qué días están abiertos", "horas de atención", "horarios"]
    a: "Nuestro horario es de lunes a sábado, de 10:00 a.m. a 8:00 p.m. 🕗. Los domingos cerramos para recargar estilo 😎."
  - q: "ubicación"
    keywords: ["ubicación", "dónde están", "dónde queda", "cómo los encuentro", "dirección", "localización", "tienda física", "dónde se encuentran"]
    a: |-
      Somos una tienda virtual. No contamos con atención presencial, todas las compras y consultas se gestionan a través de nuestra tienda online.

      Puede ver nuestro catálogo si lo pides aquí o contactarnos por nuestra tienda virtual: {socials.instagram}

      Si necesitas conocer opciones de envío a su ciudad, indíquenos su ubicación y con gusto le informamos las alternativas y tiempos de entrega.
  - q: "precios"
    keywords: ["precios", "cuánto cuesta", "cuánto valen", "tarifas", "valor", "costos", "cuánto cobran", "cuál es el precio"]
    a: "Tenemos prendas desde $35 mil. Los precios dependen del modelo y colección 👕. ¿Quieres que te envíe el catálogo completo?"
  - q: "catálogo"
    keywords: ["catálogo", "productos", "colección", "ver catálogo", "ver productos", "mostrar catálogo", "mostrar productos"]
    a: "Puedes ver nuestro catálogo más reciente aquí 👉 {catalog.link}. ¡Todo con flow urbano garantizado!"
  - q: "envíos"
    keywords: ["envíos", "envio", "entregas", "a dónde envían", "envían a mi ciudad", "despachos", "cómo envían", "formas de envío"]
    a: "Hacemos envíos a todo el país 🇨🇴 (o donde apliques). Los pedidos se despachan en 24 a 48 horas."
  - q: "formas de pago"
    keywords: ["formas de pago", "cómo pago", "métodos de pago", "puedo pagar con tarjeta", "aceptan nequi", "aceptan daviplata", "transferencia", "cuáles son los métodos de pago"]
    a: "Aceptamos pagos por Nequi, Daviplata, transferencia bancaria y tarjeta 💳. ¡Tú eliges!"
  - q: "devoluciones"
    keywords: ["devoluciones", "cambios", "puedo cambiar", "cómo hago un cambio", "reembolsos", "puedo devolver", "devolver producto"]
    a: "Aceptamos cambios dentro de los primeros 5 días hábiles después de recibir tu pedido, siempre que la prenda esté en perfecto estado."
  - q: "novedades"
    keywords: ["novedades", "nueva colección", "nuevos productos", "lanzamientos", "lo nuevo", "últimas prendas"]
    a: "Cada semana lanzamos nuevas prendas urbanas 🔥. ¿Quieres que te avise cuando salga la próxima colección?"
  - q: "contacto"
    keywords: ["contacto", "cómo los contacto", "whatsapp", "instagram", "cómo hablo con ustedes", "atención al cliente"]
    a: "Puedes escribirnos directamente por WhatsApp o Instagram 📲. Siempre respondemos rápido."
  - q: "quiénes son"
    keywords: ["quiénes son", "quién eres", "sobre ustedes", "quién está detrás", "acerca de", "historia", "quién fundó", "quién es urban elegance"]
    a: "Somos *Urban Elegance*, una marca de ropa urbana que combina estilo, actitud y elegancia. Diseñamos prendas únicas para quienes marcan tendencia."
  - q: "redes sociales"
    keywords: ["redes sociales", "instagram", "tiktok", "facebook", "síguenos", "dónde ver más", "perfil social"]
    a: "Síguenos en Instagram y TikTok como *@UrbanElegance* para no perderte lo nuevo 💥."
  # =============================
  # Mensajes de cada flujo (tickets, escalación, etc.)
  # =============================
  escalation:
    enabled: true
    message: "Voy a derivarte con un agente. Deja tu nombre y correo, por favor."
    thanks_message: "¡Gracias! Un agente te contactará pronto."
  tickets:
    enabled: true
    message_ask_detail: "Por favor, describe brevemente el inconveniente o consulta que tienes. Cuanta más información nos des, más rápido podremos ayudarte."
    message_request_contact: "¿Nos puedes dejar tu correo electrónico o número de pedido para agilizar la gestión?"
    message_opened: "¡Listo! Hemos registrado tu solicitud con el número #{ticket_id}. Nuestro equipo te contactará pronto."
    message_status_template: "Ticket #{ticket_id} - Estado actual: {status}"

  # =============================
  # Rate limiting (antispam)
  # =============================
  rate_limit:
    per_user_per_minute: 30       # Máximo de mensajes por usuario por minuto
    message: "Demasiados mensajes, intenta en un minuto."
    global_per_minute: 200        # Límite global opcional

  # =============================
  # Notificaciones a administradores (opcional)
  # =============================
  admin_notify:
    enabled: false
    channel_id: ""                # chat_id destino para avisos
    new_ticket_template: "Nuevo ticket #{ticket_id} de {user_id}: {text}"

  # =============================
  # Administración (comandos)
  # =============================
  admin:
    enabled: true
    user_ids: []                # IDs permitidos para /admin (rellena con tus IDs)
    commands_help: |
      Comandos admin:
      - /admin reset_greeting <user_id>
      - /admin clear_history <user_id>
      - /admin set_topic <user_id> <topic>

# ===============================
# Overrides de ejemplo por chat_id (avanzado)
# ===============================
# Usa el ID del chat/grupo como clave de primer nivel. Sólo declara lo que cambias respecto al default.
# Ejemplo:
# "-100123456789":
#   enabled: true
#   features:
#     faq:
#       enabled: false
#   menus:
#     ...
