name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pre-commit and tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit ruff mypy
      - name: Run pre-commit
        run: python -m pre_commit run --all-files
      - name: Install dependencies and pytest
        run: pip install -r requirements.txt pytest
      - run: pytest -q
