name: CI
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Lint, type-check and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}-py${{ matrix.python-version }}

      - name: Install dependencies (dev)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run pre-commit (format/lint checks)
        run: |
          python -m pre_commit run --all-files || true

      - name: Run ruff (fast linter)
        run: |
          if command -v ruff >/dev/null 2>&1; then ruff check . || true; fi

      - name: Run mypy (type checks)
        run: |
          if command -v mypy >/dev/null 2>&1; then mypy src || true; fi

      - name: Run tests with coverage
        env:
          PYTHONPATH: .
        run: |
          pytest --cov=src --cov-report=xml --cov-report=term-missing -q

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
